# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_prueba1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(289, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.especificaciones_label = QtWidgets.QLabel(self.centralwidget)
        self.especificaciones_label.setGeometry(QtCore.QRect(10, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        self.especificaciones_label.setFont(font)
        self.especificaciones_label.setObjectName("especificaciones_label")
        self.posicion_label = QtWidgets.QLabel(self.centralwidget)
        self.posicion_label.setGeometry(QtCore.QRect(10, 180, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        self.posicion_label.setFont(font)
        self.posicion_label.setObjectName("posicion_label")
        self.radio_label = QtWidgets.QLabel(self.centralwidget)
        self.radio_label.setGeometry(QtCore.QRect(20, 60, 47, 16))
        self.radio_label.setObjectName("radio_label")
        self.gros_label = QtWidgets.QLabel(self.centralwidget)
        self.gros_label.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.gros_label.setObjectName("gros_label")
        self.ro_ventana_label = QtWidgets.QLabel(self.centralwidget)
        self.ro_ventana_label.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.ro_ventana_label.setObjectName("ro_ventana_label")
        self.ro_detector_label = QtWidgets.QLabel(self.centralwidget)
        self.ro_detector_label.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.ro_detector_label.setObjectName("ro_detector_label")
        self.radio_input = QtWidgets.QLineEdit(self.centralwidget)
        self.radio_input.setGeometry(QtCore.QRect(60, 60, 41, 20))
        self.radio_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.radio_input.setObjectName("radio_input")
        self.largo_label = QtWidgets.QLabel(self.centralwidget)
        self.largo_label.setGeometry(QtCore.QRect(150, 60, 47, 16))
        self.largo_label.setObjectName("largo_label")
        self.largo_input = QtWidgets.QLineEdit(self.centralwidget)
        self.largo_input.setGeometry(QtCore.QRect(190, 60, 51, 20))
        self.largo_input.setObjectName("largo_input")
        self.gros_input = QtWidgets.QLineEdit(self.centralwidget)
        self.gros_input.setGeometry(QtCore.QRect(150, 90, 91, 20))
        self.gros_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gros_input.setObjectName("gros_input")
        self.ro_ventana_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ro_ventana_input.setGeometry(QtCore.QRect(150, 120, 91, 20))
        self.ro_ventana_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ro_ventana_input.setObjectName("ro_ventana_input")
        self.ro_detector_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ro_detector_input.setGeometry(QtCore.QRect(150, 150, 91, 20))
        self.ro_detector_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ro_detector_input.setObjectName("ro_detector_input")
        self.corr_label = QtWidgets.QLabel(self.centralwidget)
        self.corr_label.setGeometry(QtCore.QRect(20, 230, 131, 16))
        self.corr_label.setObjectName("corr_label")
        self.dist_fd_label = QtWidgets.QLabel(self.centralwidget)
        self.dist_fd_label.setGeometry(QtCore.QRect(20, 260, 161, 16))
        self.dist_fd_label.setObjectName("dist_fd_label")
        self.corr_input = QtWidgets.QLineEdit(self.centralwidget)
        self.corr_input.setGeometry(QtCore.QRect(170, 230, 61, 20))
        self.corr_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.corr_input.setObjectName("corr_input")
        self.dist_fdi_input = QtWidgets.QLineEdit(self.centralwidget)
        self.dist_fdi_input.setGeometry(QtCore.QRect(30, 300, 41, 20))
        self.dist_fdi_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dist_fdi_input.setObjectName("dist_fdi_input")
        self.dist_fdf_input = QtWidgets.QLineEdit(self.centralwidget)
        self.dist_fdf_input.setGeometry(QtCore.QRect(110, 300, 41, 20))
        self.dist_fdf_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dist_fdf_input.setObjectName("dist_fdf_input")
        self.dist_fdi_label = QtWidgets.QLabel(self.centralwidget)
        self.dist_fdi_label.setGeometry(QtCore.QRect(30, 280, 47, 16))
        self.dist_fdi_label.setObjectName("dist_fdi_label")
        self.dist_fdf_label = QtWidgets.QLabel(self.centralwidget)
        self.dist_fdf_label.setGeometry(QtCore.QRect(110, 280, 47, 16))
        self.dist_fdf_label.setObjectName("dist_fdf_label")
        self.dist_fds_label = QtWidgets.QLabel(self.centralwidget)
        self.dist_fds_label.setGeometry(QtCore.QRect(190, 280, 47, 16))
        self.dist_fds_label.setObjectName("dist_fds_label")
        self.dist_fds_input = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dist_fds_input.setGeometry(QtCore.QRect(190, 300, 51, 22))
        self.dist_fds_input.setSingleStep(0.1)
        self.dist_fds_input.setObjectName("dist_fds_input")
        self.get_e_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_e_button.setGeometry(QtCore.QRect(160, 350, 111, 23))
        self.get_e_button.setObjectName("get_e_button")
        self.cm_1 = QtWidgets.QLabel(self.centralwidget)
        self.cm_1.setGeometry(QtCore.QRect(110, 60, 31, 16))
        self.cm_1.setObjectName("cm_1")
        self.cm_2 = QtWidgets.QLabel(self.centralwidget)
        self.cm_2.setGeometry(QtCore.QRect(250, 60, 31, 16))
        self.cm_2.setObjectName("cm_2")
        self.cm_3 = QtWidgets.QLabel(self.centralwidget)
        self.cm_3.setGeometry(QtCore.QRect(250, 300, 31, 16))
        self.cm_3.setObjectName("cm_3")
        self.cm_4 = QtWidgets.QLabel(self.centralwidget)
        self.cm_4.setGeometry(QtCore.QRect(160, 300, 31, 16))
        self.cm_4.setObjectName("cm_4")
        self.cm_5 = QtWidgets.QLabel(self.centralwidget)
        self.cm_5.setGeometry(QtCore.QRect(80, 300, 31, 16))
        self.cm_5.setObjectName("cm_5")
        self.mm_1 = QtWidgets.QLabel(self.centralwidget)
        self.mm_1.setGeometry(QtCore.QRect(250, 90, 31, 16))
        self.mm_1.setObjectName("mm_1")
        self.ro_1 = QtWidgets.QLabel(self.centralwidget)
        self.ro_1.setGeometry(QtCore.QRect(250, 120, 31, 16))
        self.ro_1.setObjectName("ro_1")
        self.ro_2 = QtWidgets.QLabel(self.centralwidget)
        self.ro_2.setGeometry(QtCore.QRect(250, 150, 31, 16))
        self.ro_2.setObjectName("ro_2")
        self.cm_6 = QtWidgets.QLabel(self.centralwidget)
        self.cm_6.setGeometry(QtCore.QRect(240, 230, 31, 16))
        self.cm_6.setObjectName("cm_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.especificaciones_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Especificaciones del Detector</span></p></body></html>"))
        self.posicion_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Posicion de la Fuente</span></p></body></html>"))
        self.radio_label.setText(_translate("MainWindow", "Radio :"))
        self.gros_label.setText(_translate("MainWindow", "Grosor Ventana :"))
        self.ro_ventana_label.setText(_translate("MainWindow", "Densidad Ventana :"))
        self.ro_detector_label.setText(_translate("MainWindow", "Densidad Detector :"))
        self.radio_input.setText(_translate("MainWindow", "2.54"))
        self.largo_label.setText(_translate("MainWindow", "Largo :"))
        self.largo_input.setText(_translate("MainWindow", "5.08"))
        self.gros_input.setText(_translate("MainWindow", "0.0508"))
        self.ro_ventana_input.setText(_translate("MainWindow", "2.6984"))
        self.ro_detector_input.setText(_translate("MainWindow", "3.67"))
        self.corr_label.setText(_translate("MainWindow", "Corrimiento del eje :"))
        self.dist_fd_label.setText(_translate("MainWindow", "Distancias Fuente-Detector:"))
        self.corr_input.setText(_translate("MainWindow", "0"))
        self.dist_fdi_input.setText(_translate("MainWindow", "0"))
        self.dist_fdf_input.setText(_translate("MainWindow", "0"))
        self.dist_fdi_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Inicio</p></body></html>"))
        self.dist_fdf_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Final</p></body></html>"))
        self.dist_fds_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Paso</p></body></html>"))
        self.get_e_button.setText(_translate("MainWindow", "Obtener Energias"))
        self.cm_1.setText(_translate("MainWindow", "cm"))
        self.cm_2.setText(_translate("MainWindow", "cm"))
        self.cm_3.setText(_translate("MainWindow", "cm"))
        self.cm_4.setText(_translate("MainWindow", "cm"))
        self.cm_5.setText(_translate("MainWindow", "cm"))
        self.mm_1.setText(_translate("MainWindow", "mm"))
        self.ro_1.setText(_translate("MainWindow", "gr/cm³"))
        self.ro_2.setText(_translate("MainWindow", "gr/cm³"))
        self.cm_6.setText(_translate("MainWindow", "cm"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

